# deploy.yml
---
- hosts: webservers
  become: yes
  roles:
    - ./ansible/deployer

  vars:
    docker_image_name: "shegerlab2024.jfrog.io/petclinic/petclinic:{{ build_number }}" # Use build number for the tag
    app_port: 8081 # Change this as needed